spring:
  profiles:
    active: dev
  application:
    name: sell-system
  datasource:
    url: jdbc:mysql://${sell-system.mysql.ip}:${sell-system.mysql.port}/${sell-system.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${sell-system.mysql.username}
    password: ${sell-system.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      #????30????????1800?
      max-lifetime: 30000
      idle-timeout: 10000
      connection-test-query: SELECT 1
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
  flyway:
    enabled: true
    # flyway ? clean ??????? schema ???? table, ????????????? false ???????????????
    clean-disabled: true
    locations: classpath:db.migration
    table: flyway_schema_history
    baseline-on-migrate: true
    # ?? baseline ????,???? 1, ??????? SQL ??, migrate ?????
    baseline-version: 1
    encoding: UTF-8
    # ?????????? ???? true  ???? false
    out-of-order: false
    schemas: ${sell-system.mysql.db}
    # ?????????????   ??? ??????? ?? ????? DML ??? ???DDL ?????
    validate-on-migrate: true
  servlet: #??????????10MB?????????50MB??
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: ${sell-system.server.port}

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: ${mybatis-plus.log.impl}
    map-underscore-to-camel-case: true

swagger:
  basic:
    enabled: ${swagger.enabled}

page helper:
  # pageSize=0????????
  page-size-zero: true
  # ??????????????????????
  reasonable: true
  auto-dialect-class: hikari
  auto-dialect: true
  default-count: false

token:
  jwtSecretKey: ${sell-system.token.jwtSecretKey}